name: Require PR for main branch changes
on:
  push:
    branches:
      - main
jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent direct push to main
        run: |
          echo "Direct pushes to main are not allowed. Please open a pull request."
          exit 1